//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Funeral_Service_1.db
{
    using System;
    using System.Collections.Generic;
    
    public partial class Basket
    {
        public int ID_Basket { get; set; }
        public Nullable<int> Count { get; set; }
        public Nullable<int> ID_Service { get; set; }
        public Nullable<int> ID_Graveyard { get; set; }
        public Nullable<int> ID_Product { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<int> ID_User { get; set; }
    
        public virtual Graveyard Graveyard { get; set; }
        public virtual Product Product { get; set; }
        public virtual Service Service { get; set; }
        public virtual C_User C_User { get; set; }
    }
}
