//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Funeral_Service_1.db
{
    using System;
    using System.Collections.Generic;
    
    public partial class Graveyard
    {
        public int ID_Graveyard { get; set; }
        public string Graveyard_Name { get; set; }
        public string Graveyard_Location { get; set; }
        public Nullable<int> ID_Service { get; set; }
        public Nullable<int> ID_Role { get; set; }
    
        public virtual Role Role { get; set; }
        public virtual Service Service { get; set; }
    }
}
